config/routes.rb
FoodDelivery::Application.routes.draw do

  resources :restaurants, only: [:new, :create, :show] # temporary, we can add the other actions later.
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root    :to => 'Pages#home'

  match '/adnew',     :to => 'Restaurants#new'
  
	match '/signup',		:to => 'Users#new'
	
	match '/signin',    :to => 'sessions#new'
	match '/signout',   :to => 'sessions#destroy', via: :delete 

  match '/about',  		:to => 'Pages#about'
  match '/faq',    		:to => 'Pages#faq'
  match '/contact',		:to => 'Pages#contact'

end

app/models/meal.rb
class Meal < ActiveRecord::Base
	belongs_to :restaurant
	attr_accessible(:name, :price)

# having issues getting this REGEX to work properly, Rubular says its fine
# but the test suite isn't passing. Either the test is written incorrectly,
# or theres something wrong here

	VALID_PRICE_REGEX = /\d{1,}[.]\d{2}/
	validates :name, presence: true, length: { maximum: 50 }
	validates :price, presence: true, format: { with: VALID_PRICE_REGEX }
end
# == Schema Information
#
# Table name: meals
#
#  id            :integer         not null, primary key
#  name          :string(255)
#  price         :decimal(, )
#  created_at    :datetime        not null
#  updated_at    :datetime        not null
#  restaurant_id :integer
#

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :meals, dependent: :destroy

	attr_accessible(:name, :description)

	validates :name, presence: true, length: { maximum: 50 }
	validates :description, presence: true
end
# == Schema Information
#
# Table name: restaurants
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible(:name, :email, :cardnumber, :password, :password_confirmation)
  has_secure_password
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_CARDNUMBER_REGEX = /\d{9}/
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
            uniqueness: { case_sensitive: false }
  validates :cardnumber, presence: true, format: { with: VALID_CARDNUMBER_REGEX },
            length: { is: 9 }, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  
  private
  
    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)
#  email           :string(255)
#  cardnumber      :string(255)
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean         default(FALSE)
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  end

  def faq
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    # this action should be protected so that only users with admin=true can axx
		@restaurant = Restaurant.new
  end

  def create
    # this action should be protected so that only users with admin=true can axx
		@restaurant = Restaurant.new(params[:restaurant])
    if @restaurant.save
     flash.now[:success] = "Restaurant added!"
     render 'new'
    else
    render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = "Welcome Back to Duke Delivery!"
      redirect_to user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Duke Delivery!"
      redirect_to @user
    else
      render 'new'
    end 
  end
end

private
  
  # This method can be used to define a before filter for certain actions. May need to move it into a helper file
  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Err...
  # Basically allows for easy (dynamic) manipulation of title on a page by page basis
  
  def full_title(page_title)
    base_title = "Duke Delivery"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def sign_out
    current_user = nil
    cookies.delete(:remember_token)
  end
  
  private
  
    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Created by a Duke Alumnus
    </small>
    <nav>
      <ul>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Duke Delivery", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "FAQ",    faq_path %></li>
		  <% if signed_in? %>
		 	<li id="fat-menu" class="dropdown">
		  	  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Account <b class="caret"></b>
		  	  </a>
		  	  <ul class="dropdown-menu">
		  	    <li><%= link_to "Statistics", current_user %></li>
			    <li><%= link_to "Settings", '#' %></li>
			    <li class="divider"></li>
			    <li>
			      <%= link_to "Sign out", signout_path, method: "delete" %>
			    </li>
		      </ul>
		    </li>
          <% else %>
			<li><%= link_to "Sign in", signin_path %></li>
		  <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
	
	<!-- There is a formatting error in the flash message, it is sticking to the header -->
	
	<% flash.each do |key, value| %>
	  <div class="alert alert-<%=key %>"><%= value %></div>
	<% end %>
	</div>
	<%= yield %>
  <%= render 'layouts/footer' %>
  <div class ="container">
		<%= debug(params) if Rails.env.development? %>	
  </div>
</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About Us')%>
<div class="container bump2">
	<div class="row">
		<span class="span10 offset1">
		<h1 class="hero">What are we about?</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</span>
	</div>

	<div class="row">
		<span class="span10 offset1">
		  <h1 class="hero">Meet the team!</h1>
		</span>	
		<span class="span8 offset1">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</span>
		<span class="span2">
			<ul class="thumbnails">
			  <li class="span2">
			    <a href="#" class="thumbnail">
			      <img src="/assets/tuhin.jpg" alt="">
			    </a>
			  </li>
			</ul>
		</span>
	</div>

	<div class="row">
		<span class="span2 offset1">
			<ul class="thumbnails">
			  <li class="span2">
			    <a href="#" class="thumbnail">
			      <img src="/assets/tushar.jpg" alt="">
			    </a>
			  </li>
			</ul>
		</span>
		<span class="span8">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</span>
	</div>
</div>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us')%>
<div class="container stretch bump1">
  <div class="hero">
    <h1>Questions or Comments?</h1>
  </div>
</div>

<div class="container bump1">
	<div class="row">
		<span class="span10 offset1">
			<h2>Go ahead, send us an email!</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</span>
	</div>
</div>

app/views/pages/faq.html.erb
<% provide(:title, 'FAQ')%>
<div class="container stretch bump1">
  <div class="hero">
    <h1>Frequently Asked Questions</h1>
  </div>
</div>

<div class="container bump1">
  <div class="row">
    <span class="span10 offset1">
      <dl><dt>How do I order food?</dt>
      <dd>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat.
      </dd></dl>
      <dl><dt>How do you make money?</dt>
      <dd>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. 
      </dd></dl>
      <dl><dt>How do I add my business?</dt>
      <dd>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco.
      </dd></dl>
      <dl><dt>Where can I get X dish?</dt>
      <dd>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
        tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.
      </dd></dl>
    </span>
  </div>
</div>

app/views/pages/home.html.erb
<% provide(:title, 'Home')%>
<div class ="container stretch">
 <div class="center hero-unit">
   <h1>Local foods, delivered.</h1>
   <h2>Order and enjoy right from your couch!</h2>
   <%= link_to "Get Started!", signup_path, class: "btn btn-large btn-success" %>
 </div>
</div>
<div class="container">
  <div class="row">
    <div class ="span4">
      <h2>Order directly</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
    </div>
    <div class ="span4">
      <h2>See what's popular</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
    </div>
    <div class ="span4">
      <h2>Ditch the phone</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<%= provide(:title, "Admin")%>
<br>
<h1>Add a restaurant</h1>
<div class="container">
	<div class="row">
		<div class="span6 offset3">
			<%= form_for(@restaurant) do |f| %>
				<%= render 'shared/error_messages', :object => f.object %>

				<%= f.label :name %>
			  <%= f.text_field :name %>

			  <%= f.label :description %>
			  <%= f.text_field :description %>

			  <%= f.submit "Add to database", :class => "btn btn-large btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/restaurants/show.html.erb
<% provide(:title, @restaurant.name) %>
<br>
<div class="container">
	<div class="row">
		<h1><%= @restaurant.name %></h1>
		<hr>
	</div>
</div>

app/views/shared/_error_messages.erb
<!-- This code will display form submission error messages! -->
<!-- I had to adjust the partial to accept an object named 'object',
before it was using the instance variable "@user" -->

<% if object.errors.any? %>
  <div id="error_explanation">
	<div class="alert alert-error">
		Umm, dude you made <%= pluralize(object.errors.count, "mistake") %>.
	</div>
	<ul>
	<% object.errors.full_messages.each do |msg| %>
	  <li>* <%= msg %></li>
	<% end %>
	</ul>
  </div>
<% end %>

app/views/users/new.html.erb
<%= provide(:title, "Sign up!")%>
<br>
<h1>Sign up!</h1>
<div class="container">
	<div class="row">
	  <div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		  <%= render 'shared/error_messages', :object => f.object %>
		
		  <%= f.label :name %>
		  <%= f.text_field :name %>

		  <%= f.label :email %>
		  <%= f.text_field :email %>
		
		  <%= f.label :cardnumber, "DukeCard Number" %>
		  <%= f.text_field :cardnumber %>
		
		  <%= f.label :password %>
		  <%= f.password_field :password %>
		
		  <%= f.label :password_confirmation, "Confirmation" %>
		  <%= f.password_field :password_confirmation %>
		
		  <%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>
		<% end %>
	  </div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>